apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "bar.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  namespaceSelector:
    matchNames:
    - r4j-testing
  selector:
    matchLabels:
      {{- include "bar.selectorLabels" . | nindent 6 }}
  endpoints:
  - path: /actuator/prometheus
    port: "http"